name: build


on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda

    - name: Build Plugin
      run: ./gradlew buildPlugin


    - name: Generate Release Notes
      uses: release-drafter/release-drafter@v6
      with:
        version: ${{ steps.read-properties.outputs.version }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish Release
      uses: alexellis/upload-assets@0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        asset_paths: '["build/distributions/*.zip"]'
#      uses: softprops/action-gh-release@v2
#      with:
#        files: |
#          build/distributions/*.zip
#        token: ${{ secrets.GITHUB_TOKEN }}

